### ISSUE TITLE
"No OpenStack4j connector found in classpath"

### ISSUE THREAD

**Issue by tiefpunkt** [hubecker/lvm-openstack-adapters#1]
We installed a fresh LVM 2.1 system, and deployed the OpenStack Adapter. When setting up the block storage adapter, we filled out all the necessary fields, and then wanted to test the connection. After clicking the "Test Connection" button, we are greeted with an exception (see screenshot).

![image001](https://cloud.githubusercontent.com/assets/434444/14633851/bd7ac856-061f-11e6-8f06-7ee96664b75b.png)

I checked on the filesystem, the connector "openstack4j-httpclient" that you seem to have chosen, is actually available, but for some reason the java stack doesn't find it. Any idea on this?

**Comment by seand9** [comment]
This error comes from line 32 in: http://grepcode.com/file/repo1.maven.org/maven2/org.pacesys/openstack4j/2.0.4/org/openstack4j/core/transport/internal/HttpExecutor.java

The HttpExecutorService class is implemented in: openstack4j-jersey2-jdk16-2.0.4.jar.
Can you check if that jar file is on the filesystem as well and try restarting LVM?
Which version of java are you using? This jersey version was used to because it's compatible with java 1.6; are there any other jersey libs on the classpath?

**Comment by seand9** [comment]
Which version (SP) of LVM did you deploy? I have not been able to reproduce this issue with the latest release but older versions may be subject to this issue.

**Comment by seand9** [comment]
Seems like the classpath issue has disappeared after upgrading to Openstack4j v. 2.20.
